### ISSUE TITLE
Entity focus after associating to an entity

### ISSUE THREAD

**Issue by johncordeiro** [push-flow/bothub#100]
Remove focus after associating it to an entity and avoid to duplicate entities to the same word:

<img width="418" alt="screen shot 2018-06-04 at 10 35 14 am" src="https://user-images.githubusercontent.com/6073075/40926471-a96e6ac0-67f2-11e8-9a91-2139e12eac51.png">

**Comment by douglasppaz** [comment]
Moved to https://github.com/push-flow/bothub-webapp/issues/83
