### ISSUE TITLE
Deleting and creating a new sample

### ISSUE THREAD

**Issue by johncordeiro** [push-flow/bothub#101]
After deleting and creating a new sample, the new sample doesn't show up in the Example list below it, because of an index issue.

<img width="495" alt="screen shot 2018-06-04 at 12 29 10 pm" src="https://user-images.githubusercontent.com/6073075/40926586-e74c4c90-67f2-11e8-8964-e682efc2cec3.png">

**Comment by douglasppaz** [comment]
Reported in https://github.com/push-flow/bothub-webapp/issues/84
