### ISSUE TITLE
Improve search layout

### ISSUE THREAD

**Issue by johncordeiro** [push-flow/bothub#89]
On the search layout, the text typed it's at the same color as the placeholder, which is not common in this kind of action

<img width="732" alt="screen shot 2018-06-04 at 11 50 00 am" src="https://user-images.githubusercontent.com/6073075/40924378-852859f0-67ed-11e8-86f7-ff73d35ed37d.png">

**Comment by douglasppaz** [comment]
Moved to https://github.com/push-flow/bothub-webapp/issues/75
