### ISSUE TITLE
Configure favicon

### ISSUE THREAD

**Issue by johncordeiro** [push-flow/bothub#90]
Add favicon to the Bothub Webapp

<img width="249" alt="screen shot 2018-06-04 at 11 51 55 am" src="https://user-images.githubusercontent.com/6073075/40924476-b1b609a4-67ed-11e8-8a6e-bb4ef4e03609.png">

**Comment by douglasppaz** [comment]
Moved to https://github.com/push-flow/bothub-webapp/issues/74
