### ISSUE TITLE
Add loading to forms loading

### ISSUE THREAD

**Issue by johncordeiro** [push-flow/bothub#93]
Add loading widget when getting forms from the Backend to avoid strange behaviors, when opening modals:

<img width="651" alt="screen shot 2018-06-04 at 12 00 01 pm" src="https://user-images.githubusercontent.com/6073075/40925001-03747ac2-67ef-11e8-884b-b255172171d8.png">

**Comment by douglasppaz** [comment]
Moved to https://github.com/push-flow/bothub-webapp/issues/78
