### ISSUE TITLE
Update authentication modal text

### ISSUE THREAD

**Issue by johncordeiro** [push-flow/bothub#94]
- Replace the text "Me Registered" to "Create account"
- Replace the text "I have registered" to "Login"

<img width="646" alt="screen shot 2018-06-04 at 12 03 36 pm" src="https://user-images.githubusercontent.com/6073075/40925127-566f7bfa-67ef-11e8-9082-7141c8d93189.png">

**Comment by douglasppaz** [comment]
Moved to https://github.com/push-flow/bothub-webapp/issues/79
